services:
  db:
    image: postgres
    container_name: escola
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: escola
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: